/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void draw_shop(PApplet appc, GWinData data) {
  
}

public void windowMouse(PApplet appc, GWinData data, MouseEvent event) {
  if (event.getAction() == MouseEvent.CLICK){ //?? 
    iconClicked();
    for(int i = 0; i < itemShop.stock.size(); i ++){
      itemShop.stock.get(i).buyButtClicked();
    }
  }
  
}

// Create all the GUI controls.
// autogenerated do not edit

public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");

  shopWindow = GWindow.getWindow(this, "shop", 0, 200, 400, 500, JAVA2D);
  shopWindow.setActionOnClose(G4P.KEEP_OPEN);
  shopWindow.addDrawHandler(this, "draw_shop");
  shopWindow.addMouseHandler(this, "windowMouse");
  
  label = new GLabel(shopWindow, 200, -40, 200, 500);
  label.setFont(new Font("Monospaced", Font.PLAIN, 20));
  label.setLocalColor(2, color(0,0,0));
  label.setText("");
  
  priceLabel = new GLabel(shopWindow, 330, 70, 70, 50);
  priceLabel.setFont(new Font("Monospaced", Font.PLAIN, 20));
  priceLabel.setLocalColor(2, color(0,0,0));
  priceLabel.setText("");
  
  buyLabel = new GLabel(shopWindow, 228, 70, 50, 50);
  buyLabel.setFont(new Font("Monospaced", Font.PLAIN, 20));
  buyLabel.setLocalColor(2, color(0,0,0));
  buyLabel.setText("");
  
  moneyLabel = new GLabel(shopWindow, 250, -21, 150, 100);
  moneyLabel.setFont(new Font("Monospaced", Font.PLAIN, 20));
  moneyLabel.setLocalColor(2, color(0,0,0));
  moneyLabel.setText("");
  
  usesLabel = new GLabel(shopWindow, 220, 110, 180, 50);
  usesLabel.setFont(new Font("Monospaced", Font.PLAIN, 20));
  usesLabel.setLocalColor(2, color(0,0,0));
  usesLabel.setText("");
  
  shopWindow.background(255);
  shopWindow.frameRate(60);
  shopWindow.loop();
  for(int i = 0; i < 20; i++){
    int x = 0;
    int y = 0;
    PImage temp = loadImage("images/money.png");
    temp.resize(50, 50);
    shopWindow.image(temp, 200, 0);
    for( int j = 0 ; j < itemShop.stock.size(); j++){ 
      outline(x, y, size, 0);
      shopWindow.image(itemShop.stock.get(j).icon, x, y);
      x += size;
      if(i%4 == 3){
        x = 0;
        y += size;
      }
    }  
  }
  
}


// Variable declarations 
// autogenerated do not edit
GWindow shopWindow;
GImageButton img; 
GLabel buyLabel, moneyLabel, label, priceLabel, usesLabel;
