/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) {
  appc.background(230);
}

synchronized public void win_draw(PApplet appc, GWinData data, PImage a, int x, int y) {
  println("running function");
  appc.image(a, x, y);
}

// Create all the GUI controls.
// autogenerated do not edit

public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  shopWindow = GWindow.getWindow(this, "shop", 0, 0, 500, 500, JAVA2D);
  shopWindow.setVisible(false);
  shopWindow.noLoop();
  
  shopWindow.setActionOnClose(G4P.CLOSE_WINDOW);
  shopWindow.addDrawHandler(this, "draw_shop");
  shopWindow.loop();
  shopWindow.addDrawHandler(this, "win_draw");
  
}




// Variable declarations 
// autogenerated do not edit
GWindow shopWindow;
GCustomSlider speedSlider; 
